# Generated by Django 5.1.15 on 2026-09-17 15:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='Ticketera MCTI', max_length=200)),
                ('nombre_corto', models.CharField(default='Ticketera', max_length=50)),
                ('logo_pequeño', models.FileField(blank=True, default='', upload_to='config/')),
                ('logo_grande', models.FileField(blank=True, default='', upload_to='config/')),
                ('color_logo', models.CharField(default='#065E94', max_length=7)),
                ('color_fondo_logo', models.CharField(default='#FFFFFF', max_length=7)),
                ('color_sitio', models.CharField(default='#065E94', max_length=7)),
                ('max_file_size_mb', models.IntegerField(default=10, verbose_name='Tamaño máximo de archivo (MB)')),
                ('allowed_file_types', models.JSONField(default=list, verbose_name='Tipos de archivo permitidos')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='WallpaperGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(blank=True, default='', max_length=10)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Grupo de Wallpapers',
                'verbose_name_plural': 'Grupos de Wallpapers',
                'db_table': 'wallpaper_groups',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('username', models.CharField(blank=True, default='', max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dependencia', models.CharField(blank=True, default='', max_length=200)),
                ('debe_cambiar_password', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarios', to='core.group')),
                ('roles', models.ManyToManyField(blank=True, related_name='usuarios', to='core.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(default='Trabajo', max_length=50)),
                ('columnas', models.JSONField(default=list)),
                ('wallpaper_path', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tableros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='tableros',
            field=models.ManyToManyField(blank=True, related_name='roles', to='core.tablero'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(default='Solicitud', max_length=100)),
                ('prioridad', models.CharField(default='Media', max_length=50)),
                ('area', models.CharField(blank=True, default='', max_length=100)),
                ('responsable', models.CharField(blank=True, default='', max_length=500)),
                ('solicitante', models.CharField(blank=True, default='', max_length=200)),
                ('seccion_solicitante', models.CharField(blank=True, default='', max_length=200)),
                ('email_solicitante', models.CharField(blank=True, default='', max_length=200)),
                ('checklist', models.JSONField(default=list)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('posicion', models.IntegerField(default=0)),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.tablero')),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['posicion', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=500)),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ticket')),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.ticket')),
            ],
            options={
                'db_table': 'comentarios',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('imagen', models.FileField(upload_to='wallpapers/')),
                ('thumb', models.FileField(blank=True, default='', upload_to='wallpapers/thumbs/')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallpapers', to='core.wallpapergroup', verbose_name='Grupo')),
            ],
            options={
                'db_table': 'wallpapers',
                'ordering': ['group__orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TableroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_tablero', models.CharField(choices=[('Administrador', 'Administrador'), ('Miembro', 'Miembro')], default='Miembro', max_length=20)),
                ('permisos', models.JSONField(blank=True, null=True)),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tablero_usuarios',
                'unique_together': {('tablero', 'usuario')},
            },
        ),
    ]
