# Generated by Django 5.1.15 on 2026-09-09 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CambioPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe_cambiar', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cambio_password_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cambio_passwords',
            },
        ),
    ]
