# Generated by Django 5.1.15 on 2026-09-14 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_debe_cambiar_password_cambiopassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='Ticketera MCTI', max_length=200)),
                ('nombre_corto', models.CharField(default='Ticketera', max_length=50)),
                ('logo_pequeño', models.FileField(blank=True, default='', upload_to='config/')),
                ('logo_grande', models.FileField(blank=True, default='', upload_to='config/')),
                ('color_logo', models.CharField(default='#065E94', max_length=7)),
                ('color_fondo_logo', models.CharField(default='#FFFFFF', max_length=7)),
                ('color_sitio', models.CharField(default='#065E94', max_length=7)),
                ('max_file_size_mb', models.IntegerField(default=10)),
                ('allowed_file_types', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='WallpaperGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(blank=True, default='', max_length=10)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Grupo de Wallpapers',
                'verbose_name_plural': 'Grupos de Wallpapers',
                'db_table': 'wallpaper_groups',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='tablero',
            name='wallpaper_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('imagen', models.FileField(upload_to='wallpapers/')),
                ('thumb', models.FileField(blank=True, default='', upload_to='wallpapers/thumbs/')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallpapers', to='core.wallpapergroup')),
            ],
            options={
                'db_table': 'wallpapers',
                'ordering': ['group__orden', 'nombre'],
            },
        ),
    ]
