# Generated by Django 5.1.15 on 2026-09-21 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wallpapergroup_icono_maxlength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=200, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True, verbose_name='Debe Cambiar Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dependencia',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Dependencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='core.group', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Esta Activo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Es Supervisor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='core.rol', verbose_name='Roles'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150, unique=True, verbose_name='Nombre de Usuario'),
        ),
    ]
