# Generated by Django 5.1.15 on 2026-09-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wallpapergroup_icono_maxlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='archivo_nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='comentario',
            name='archivo_tipo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='comentario',
            name='archivo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
