# Generated by Django 5.1.15 on 2026-09-22 13:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_apellido_alter_usuario_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['created_at'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['nombre'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='tablero',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tablero', 'verbose_name_plural': 'Tableros'},
        ),
        migrations.AlterModelOptions(
            name='tablerousuario',
            options={'verbose_name': 'Usuario de Tablero', 'verbose_name_plural': 'Usuarios de Tableros'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['posicion', '-fecha_creacion'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='wallpaper',
            options={'ordering': ['group__orden', 'nombre'], 'verbose_name': 'Wallpaper', 'verbose_name_plural': 'Wallpapers'},
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.ticket', verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='group',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Grupo'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(default=False, verbose_name='Leída'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.CharField(max_length=500, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ticket', verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Rol'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='permisos',
            field=models.JSONField(blank=True, default=dict, help_text='Permisos por defecto asignados a usuarios con este rol (JSON)', verbose_name='Permisos por Defecto'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tableros',
            field=models.ManyToManyField(blank=True, related_name='roles', to='core.tablero', verbose_name='Tableros Asociados'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='color_fondo_logo',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color de Fondo del Logo'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='color_logo',
            field=models.CharField(default='#065E94', max_length=7, verbose_name='Color del Logo'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='color_sitio',
            field=models.CharField(default='#065E94', max_length=7, verbose_name='Color del Sitio'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_grande',
            field=models.FileField(blank=True, default='', upload_to='config/', verbose_name='Logo Grande'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_pequeño',
            field=models.FileField(blank=True, default='', upload_to='config/', verbose_name='Logo Pequeño'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='nombre_corto',
            field=models.CharField(default='Ticketera', max_length=50, verbose_name='Nombre Corto'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='nombre_sistema',
            field=models.CharField(default='Ticketera MCTI', max_length=200, verbose_name='Nombre del Sistema'),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='columnas',
            field=models.JSONField(default=list, verbose_name='Columnas'),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Tablero'),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='tipo',
            field=models.CharField(default='Trabajo', max_length=50, verbose_name='Tipo de Tablero'),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='wallpaper_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ruta del Fondo de Pantalla'),
        ),
        migrations.AlterField(
            model_name='tablerousuario',
            name='permisos',
            field=models.JSONField(blank=True, null=True, verbose_name='Permisos'),
        ),
        migrations.AlterField(
            model_name='tablerousuario',
            name='rol_en_tablero',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Miembro', 'Miembro')], default='Miembro', max_length=20, verbose_name='Rol en el Tablero'),
        ),
        migrations.AlterField(
            model_name='tablerousuario',
            name='tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tablero', verbose_name='Tablero'),
        ),
        migrations.AlterField(
            model_name='tablerousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='area',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='checklist',
            field=models.JSONField(default=list, verbose_name='Lista de Tareas (Checklist)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email_solicitante',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Correo del Solicitante'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(default='Solicitud', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='posicion',
            field=models.IntegerField(default=0, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(default='Media', max_length=50, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seccion_solicitante',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Sección del Solicitante'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solicitante',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.tablero', verbose_name='Tablero'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(max_length=300, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='imagen',
            field=models.FileField(upload_to='wallpapers/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre del Wallpaper'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='thumb',
            field=models.FileField(blank=True, default='', upload_to='wallpapers/thumbs/', verbose_name='Miniatura (Thumb)'),
        ),
        migrations.AlterField(
            model_name='wallpapergroup',
            name='icono',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='wallpapergroup',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Grupo'),
        ),
        migrations.AlterField(
            model_name='wallpapergroup',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
    ]
