# Generated by Django 5.1.15 on 2026-09-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting_wallpapergroup_tablero_wallpaper_path_and_more'),
        ('core', '0004_ticket_posicion'),
    ]

    operations = [
    ]
