# Generated by Django 5.1.15 on 2026-09-16 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20260916_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['posicion', '-fecha_creacion']},
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='allowed_file_types',
            field=models.JSONField(default=list, verbose_name='Tipos de archivo permitidos'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='max_file_size_mb',
            field=models.IntegerField(default=10, verbose_name='Tamaño máximo de archivo (MB)'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallpapers', to='core.wallpapergroup', verbose_name='Grupo'),
        ),
    ]
