# Generated by Django 5.1.15 on 2026-09-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_comentario_options_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='archivo_nombre',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre del Archivo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='archivo_tipo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo del Archivo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='archivo_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='URL del Archivo'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
