# Generated by Django 5.1.15 on 2026-09-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablerousuario',
            name='rol_en_tablero',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Miembro', 'Miembro')], default='Miembro', max_length=20),
        ),
    ]
